CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DO $$
BEGIN 
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'hdms_app_role') THEN 
        CREATE ROLE hdms_app_role WITH LOGIN PASSWORD 'AppSecurePassword123!';
    END IF;
END $$;

GRANT CONNECT ON DATABASE "hospital_db" TO hdms_app_role;

GRANT USAGE ON SCHEMA public TO hdms_app_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO hdms_app_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO hdms_app_role;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO hdms_app_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public 
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO hdms_app_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public 
GRANT USAGE, SELECT ON SEQUENCES TO hdms_app_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public 
GRANT EXECUTE ON FUNCTIONS TO hdms_app_role;